{{- if .Values.ingressClassParams.create }}
apiVersion: elbv2.k8s.aws/v1beta1
kind: IngressClassParams
metadata:
  name: {{ include "aws-load-balancer-controller.ingressClassParamsName" . }}
{{- if .Values.ingressClassParams.spec }}
spec:
  {{ toYaml .Values.ingressClassParams.spec | nindent 2}}
{{- end }}
{{- end }}
